version: "3"

services:
  app:
    build: .
    container_name: stock-projection-client
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - stocknet

networks:
  stocknet:
    driver: bridge
